### ISSUE TITLE
fails to start

### ISSUE THREAD

**Issue by wmertens** [nitedani/vite-plugin-compiled-react#1]
I wanted to try it out with Qwik, it looks like there's nothing really react-specific going on so it might work.

I made a stackblitz: https://stackblitz.com/edit/qwik-starter-wmk8m7

but I get this error:

```
node_modules/vite/dist/node/chunks/dep-YJaePtkC.js:67575:42: ERROR: [plugin: externalize-deps] Failed to resolve "vite-plugin-compiled-react". This package is ESM only but it was tried to load by `require`. See https://vitejs.dev/guide/troubleshooting.html#this-package-is-esm-only for more details.
```

**Comment by nitedani** [comment]
Added "type" : "module" to package.json 
https://stackblitz.com/edit/qwik-starter-nup18q?file=package.json
This at least gets it to show something.
But, unfortunately the plugin relies on the plugin api provided by `@vitejs/plugin-react`, it doesn't work with Qwik right now.
