### ISSUE TITLE
Fails to compile with error "Cannot read properties of undefined (reading 'resolve')"

### ISSUE THREAD

**Issue by DeepAnchor** [nitedani/vite-plugin-compiled-react#2]
Hey, thanks for making this plugin. 

After adding this to my vite config, I get the error "Cannot read properties of undefined (reading 'resolve')".
When I remove the two `moduleResolverPlugin` related lines from this plugin...

`const alias = config.resolve.alias;`
https://github.com/nitedani/vite-plugin-compiled-react/blob/main/src/index.ts#L82

`babelConfig.plugins.push([moduleResolverPlugin, { alias }]);`
https://github.com/nitedani/vite-plugin-compiled-react/blob/main/src/index.ts#L98

...everything works fine. It seems that it can't find `resolve` on `config` in `reactBabel(babelConfig: ReactBabelOptions, context, config)` but having looked through a bunch of documentation, I couldn't find any information on what exactly `config` is referring to.

**Comment by nitedani** [comment]
You're right. It seems like "babel-plugin-module-resolver" is not needed anymore for aliases to work. I remember adding it, because without it, aliases broke the build. I removed it, and released 1.1.0
